# Generated by Django 5.2.6 on 2025-11-13 12:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/blog/', location='C:\\Users\\ADMIN\\Desktop\\Project\\Nehru_MLA\\server\\nehru_backend\\static\\blog'), upload_to=''),
        ),
    ]
